### ISSUE TITLE
Use hints to make assertions about the running program

### ISSUE THREAD

**Issue by Bernardstanislas** [onlydustxyz/cairo-foundry#16]
As with Protostar, assertions can be done using hints.
There might be some investigation to conduct to check how one can use Cleopatra hints to achieve this.

**Comment by oxlime** [comment]
Was able to use custom hints with cleopatra to get a less than assertion. Not sure if this is the kind of thing your looking for.
https://github.com/oxlime/cleopatra_cairo/tree/feat/hint_assertions
