### ISSUE TITLE
Remove all references to Cleopatra

### ISSUE THREAD

**Issue by Bernardstanislas** [onlydustxyz/cairo-foundry#23]
The repo currently imports the former version of `cairo-rs` called `cleopatra`, we need to get rid of it and only use `cairo-rs` from now on.

**Comment by onlydust-contributor** [comment]
@oxlime is going to work on this contribution

**Comment by onlydust-contributor** [comment]
@gaetbout is going to work on this contribution
OnlyDust link : https://app.onlydust.xyz/contributions/0x0085

**Comment by oxlime** [comment]
Only one line in the .toml

**Comment by gaetbout** [comment]
Hi,

Using the cargo command I removed the one reference existing in the toml file.

Hope it is good enough,
G.

**Comment by tdelabro** [comment]
Perfect. TY

**Comment by tdelabro** [comment]
Closed by #28
