### ISSUE TITLE
Get rid of `trace_enabled` and `print_output` parameters in cairo_run

### ISSUE THREAD

**Issue by tdelabro** [onlydustxyz/cairo-foundry#48]
We always  call `cairo_run` with those two parameters set as `false`
Better simplify the code and get rid of those parameters totally.
You will have to remove some logic inside `cairo_run`:
```

	if print_output {
		write_output(&mut cairo_runner, &mut vm)?;
	}
```
must go.

and replace `	let mut vm = VirtualMachine::new(program.prime, trace_enabled);` by `let mut vm = VirtualMachine::new(program.prime, false);`

**Comment by gdnathan** [comment]
I'd like to contribute on this

**Comment by Eikix** [comment]
Closing, as #46 solves this
