### ISSUE TITLE
Doc - Describe `pre_step_instruction` using Rustdoc comments (three slashes: ///) 

### ISSUE THREAD

**Issue by Eikix** [onlydustxyz/cairo-foundry#51]
In an effort of having fully documented code, we need hooks to be documented.

Please proceed to comment above the `pub fn pre_step_instruction` declaration in an equivalent way as `pub fn compile` is documented.

**Comment by ptisserand** [comment]
Hi, can I work on this issue?

**Comment by Eikix** [comment]
Sure thing! 🔥
