### ISSUE TITLE
Doc - Describe  `src > cli > commands > execute` module and functions using Rustdoc comments (three slashes: ///) 

### ISSUE THREAD

**Issue by Eikix** [onlydustxyz/cairo-foundry#63]
In an effort of having fully documented code, we need the way we run the tests (exec) to be documented.

In `src > cli > commands > execute`, please proceed to comment above the module and functions declarations in an equivalent way as `pub fn compile` is documented.

**Comment by gdnathan** [comment]
hey, because of #47, This issue should not be a problem anymore :)
